version: '3'
services:
  sokny:
    image: sokny
    container_name: ny
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3257:3000
    environment:
      - NODE_ENV=production
      - GENERATE_SOURCEMAP=false
    networks:
      - devops
networks:
    devops:
      external: true
